apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-demo-app
  namespace: tips-webinar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: my-demo-app
        app: my-demo-app
        version: 'cd233d1'
    spec:
      containers:
      - name: my-demo-app
        image: gcr.io/codefresh-sa/trivial-web:cd233d1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: codefresh-generated-gcr.io-gcr-colors
