apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-demo-app-a0159b8
  namespace: colors
spec:
  replicas: 1
#  selector:
#    matchLabels:
#      app: my-demo-app
#      version: 'a0159b8'
  template:
    metadata:
      labels:
        name: my-demo-app
        app: my-demo-app
        version: 'a0159b8'
    spec:
      containers:
      - name: my-demo-app
        image:  336151728602.dkr.ecr.us-east-2.amazonaws.com/trivial-web:a0159b8
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: codefresh-generated-336151728602.dkr.ecr.us-east-2.amazonaws.com-ecr-colors
