apiVersion: apps/v1
kind: Service
metadata:
  name: my-demo-app
  namespace: colors
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-demo-app
    version: 'a0159b8'
  sessionAffinity: None
  type: LoadBalancer
